# Generated by Django 5.1.3 on 2024-12-04 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state_id', models.IntegerField()),
                ('state_code', models.CharField(max_length=10)),
                ('state_name', models.CharField(max_length=255)),
                ('country_id', models.IntegerField()),
                ('country_code', models.CharField(max_length=10)),
                ('country_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('wikiDataId', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_name', models.CharField(max_length=100)),
                ('o_email', models.EmailField(max_length=254, unique=True)),
                ('o_password', models.CharField(max_length=250)),
                ('o_contact', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('o_website', models.CharField(max_length=100)),
                ('o_address', models.CharField(max_length=150)),
                ('o_country', models.CharField(blank=True, max_length=100, null=True)),
                ('o_state', models.CharField(blank=True, max_length=100, null=True)),
                ('o_city', models.CharField(blank=True, max_length=100, null=True)),
                ('o_pin_no', models.CharField(max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
    ]
