# Generated by Django 5.1.4 on 2024-12-06 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='o_pin_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Productivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('app_state', models.CharField(choices=[('productive', 'Productive'), ('unproductive', 'Un Productive'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapis.organization')),
            ],
        ),
    ]
