# Generated by Django 5.1.4 on 2024-12-06 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0002_alter_organization_o_pin_no_productivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivity',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapis.organization'),
        ),
    ]
