# Generated by Django 5.1.4 on 2024-12-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0005_remove_organization_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productivity',
            new_name='AppProductivity',
        ),
    ]
