# Generated by Django 5.1.4 on 2024-12-07 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0006_rename_productivity_appproductivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=100)),
                ('e_email', models.EmailField(max_length=254)),
                ('e_password', models.CharField(max_length=255)),
                ('e_gender', models.CharField(max_length=25)),
                ('e_contact', models.CharField(max_length=100)),
                ('e_address', models.CharField(max_length=150)),
                ('e_role', models.CharField(default='Employee', max_length=150)),
                ('monitored', models.IntegerField(default=0)),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapis.organization')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='ActivityProductivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_key_press', models.IntegerField(default=0)),
                ('no_of_mouse_press', models.IntegerField(default=0)),
                ('no_of_mouse_scroll', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapis.employee')),
            ],
            options={
                'db_table': 'activity_productivity',
            },
        ),
    ]
