# Generated by Django 5.1.4 on 2024-12-07 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0007_employee_activityproductivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_of_offline', models.CharField(max_length=250)),
                ('approved_by', models.CharField(max_length=50)),
                ('starting_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapis.employee')),
            ],
        ),
    ]
