# Generated by Django 5.1.4 on 2024-12-08 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0011_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='backendapis.organization'),
        ),
    ]
