# Generated by Django 5.1.4 on 2024-12-09 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0012_alter_notice_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keystroke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_timestamp', models.DateTimeField(auto_now_add=True)),
                ('time_range', models.CharField(max_length=20)),
                ('captured_events', models.TextField()),
                ('total_keys_pressed', models.IntegerField()),
                ('total_mouse_clicks', models.IntegerField()),
                ('total_mouse_movements', models.IntegerField()),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapis.employee')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapis.organization')),
            ],
            options={
                'db_table': 'keystrokes',
            },
        ),
    ]
