# Generated by Django 5.1.4 on 2024-12-09 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0013_keystroke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystroke',
            name='o_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapis.organization'),
        ),
    ]
