# Generated by Django 5.1.4 on 2024-12-10 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0014_alter_keystroke_o_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('employees', models.ManyToManyField(to='backendapis.employee')),
                ('manager_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='backendapis.employee')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapis.organization')),
            ],
            options={
                'db_table': 'app_departments',
            },
        ),
    ]
