# Generated by Django 5.1.4 on 2024-12-10 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0015_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityproductivity',
            name='employee',
        ),
        migrations.AddField(
            model_name='activityproductivity',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapis.departments'),
        ),
    ]
