# Generated by Django 5.1.4 on 2024-12-11 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0016_remove_activityproductivity_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityproductivity',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapis.departments', unique=True),
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_title', models.TextField(null=True)),
                ('m_process', models.CharField(max_length=200, null=True)),
                ('m_url', models.TextField(blank=True, null=True)),
                ('m_log_ts', models.CharField(max_length=200)),
                ('m_total_time_seconds', models.CharField(max_length=200, null=True)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapis.employee')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapis.organization')),
            ],
            options={
                'db_table': 'monitoring',
            },
        ),
    ]
