# Generated by Django 5.1.4 on 2024-12-11 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0017_alter_activityproductivity_department_monitoring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appproductivity',
            name='organization',
        ),
        migrations.AddField(
            model_name='appproductivity',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapis.departments'),
        ),
    ]
