# Generated by Django 5.1.4 on 2024-12-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0018_remove_appproductivity_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoring',
            name='o_id',
        ),
    ]
