# Generated by Django 5.1.4 on 2024-12-11 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0019_remove_monitoring_o_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityproductivity',
            name='no_of_key_press',
        ),
        migrations.AlterField(
            model_name='activityproductivity',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapis.departments'),
        ),
    ]
