# Generated by Django 5.1.4 on 2024-12-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0020_remove_activityproductivity_no_of_key_press_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityproductivity',
            name='no_of_key_press',
            field=models.IntegerField(default=0),
        ),
    ]
