# Generated by Django 5.1.4 on 2024-12-12 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0021_activityproductivity_no_of_key_press'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_log_ts', models.CharField(max_length=200)),
                ('c_ip_address', models.GenericIPAddressField()),
                ('c_system_status', models.CharField(default='no', max_length=50)),
                ('c_operating_system', models.CharField(max_length=255)),
                ('c_username', models.CharField(max_length=255)),
                ('c_host_name', models.CharField(max_length=100)),
                ('uuid', models.CharField(default='unknown uuid', editable=False, max_length=50)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapis.employee')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapis.organization')),
            ],
            options={
                'db_table': 'Computer',
            },
        ),
        migrations.CreateModel(
            name='ScreenShotsMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssm_img', models.CharField(max_length=255)),
                ('ssm_log_ts', models.CharField(max_length=200)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapis.employee')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapis.organization')),
            ],
            options={
                'db_table': 'ScreenShotsMonitoring',
            },
        ),
    ]
