# Generated by Django 5.1.4 on 2024-12-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0022_computer_screenshotsmonitoring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='o_id',
        ),
        migrations.RemoveField(
            model_name='screenshotsmonitoring',
            name='o_id',
        ),
    ]
