# Generated by Django 5.1.4 on 2024-12-12 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0023_remove_computer_o_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='o_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapis.organization'),
        ),
    ]
