# Generated by Django 5.1.4 on 2024-12-12 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0024_computer_o_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='e_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapis.employee'),
        ),
    ]
