# Generated by Django 5.1.4 on 2024-12-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0025_alter_computer_e_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='o_id',
        ),
    ]
