# Generated by Django 5.1.4 on 2024-12-13 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0026_remove_computer_o_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenVideoMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svm_vdo', models.CharField(max_length=255)),
                ('svm_log_ts', models.CharField(max_length=200)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapis.computer')),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapis.employee')),
            ],
        ),
    ]
