# Generated by Django 5.1.4 on 2024-12-13 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0027_screenvideomonitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshotsmonitoring',
            name='c_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapis.computer'),
        ),
    ]
